version: '2'
services:
  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/logs:/var/log/nginx
    network_mode: "host"
    ports:
      - "443:443"
      - "80:80"
