version: '2'
services:
  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/logs:/var/log/nginx
    network_mode: "host"
    ports:
      - "443:443"
      - "80:80"

  mysql:
    image: mysql:8
    environment:
      - "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    cap_add:
      - ALL
    # development only
    ports:
      - "13306:3306"

volumes:
  mysql:
