version: '2'
services:
  isucoin:
    environment:
      ISU_APP_PORT:    '5000'
      ISU_DB_HOST:     '172.16.57.1'
      ISU_DB_PORT:     '13306'
      ISU_DB_USER:     'isucon'
      ISU_DB_PASSWORD: 'isucon'
      ISU_DB_NAME:     'isucoin'
      ISU_PUBLIC_DIR:  '/public'
    network_mode: "host"
    ports:
      - "5000:5000"
    volumes:
      - ./public:/public
  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - ./public:/public
      - ./nginx:/etc/nginx
      - ./nginx/logs:/var/log/nginx
    network_mode: "host"
    ports:
      - "443:443"
      - "80:80"
